In [1]:
import sys, cv2, glob, os, time
import pandas as pd  
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt 
from sklearn.utils import shuffle  

In [2]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
import os

import cv2

from sklearn.utils import shuffle

import numpy as np

def get_images(directory):

    Images = []

    Labels = []  # 0 non_diabetic , 1 for diabetic

    for labels in os.listdir(directory): #Main Directory where each class label is present as folder name.   

        for image_file in os.listdir(directory+labels): #Extracting the file name of the image from Class Label folder

            image = cv2.imread(directory+labels+r'/'+image_file) #Reading the image (OpenCV)

            image = cv2.resize(image,(150,150)) #Resize the image, Some images are different sizes. (Resizing is very Important)

            Images.append(image)

            Labels.append(labels)

    return shuffle(Images,Labels,random_state=817328462) #Shuffle the dataset you just prepared.

#Train data



In [4]:
ImagesC, LabelsC = get_images("Data\\Conjuctiva\\") #Extract the training images from the folders.

ImagesC = np.array(ImagesC) #converting the list of images to numpy array.

LabelsC = np.array(LabelsC)

In [5]:
from collections import Counter
Counter(LabelsC)

Counter({'non_diabetic': 286, 'diabetic': 286})

In [6]:
# Calculate the number of samples in ImagesC. 
n_samplesC = len(ImagesC)

# Reshape ImagesC into a 2D array.
# The new shape is (n_samplesC, -1), where n_samplesC is the number of samples (or images) and -1 is a placeholder
# that tells numpy to calculate the size of the second dimension such that the total size of the array remains the same.
# For instance, if each image is a 150x150 pixel grayscale image, then after reshaping, each image will be represented 
# as a 1D array of 150x150=22500 pixels.
# This is often done in machine learning when you want to treat each pixel as a separate feature.
data_imagesRGBC = ImagesC.reshape((n_samplesC, -1))


In [7]:
# Import the LabelEncoder class from sklearn's preprocessing module. 
# LabelEncoder is used to convert categorical data, or text data, into numbers,
# which our predictive models can better understand.
from sklearn.preprocessing import LabelEncoder

# Instantiate the LabelEncoder
# This creates an instance of LabelEncoder, which we assign to the variable `label_encoder`.
label_encoder = LabelEncoder()

# Fit and transform the LabelsC data using the LabelEncoder.
# The fit_transform() function first learns the mapping (fitting) from labels to numbers,
# and then transforms the input data to its encoded form. The input data is expected to be in a 1D array format.
# The transformed (encoded) data is then converted to a numpy array and assigned to `YC`.
YC = np.array(label_encoder.fit_transform(LabelsC))


In [8]:
#label check
from collections import Counter
Counter(YC)

Counter({1: 286, 0: 286})

In [9]:
ImagesI, LabelsI = get_images("Data\\Iris - Small\\") #Extract the training images from the folders.

ImagesI = np.array(ImagesI) #converting the list of images to numpy array.

LabelsI = np.array(LabelsI)

In [10]:
from collections import Counter
Counter(LabelsI)

Counter({'non_diabetic': 286, 'diabetic': 286})

In [11]:
n_samplesI = len(ImagesI)
data_imagesRGBI = ImagesI.reshape((n_samplesI, -1))

In [12]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
YI = np.array(label_encoder.fit_transform(LabelsI))

In [13]:
from collections import Counter
Counter(YI)

Counter({1: 286, 0: 286})

In [14]:
#Combining the features 
combined_features = np.concatenate((data_imagesRGBC, data_imagesRGBI), axis=1)

In [15]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(combined_features, YI, test_size=0.15, shuffle=True)

# Combine using Original Features

In [16]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [17]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("SVC with Polynomial Kernel")
svm = SVC(kernel='poly', C=3.0, random_state=42)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


SVC with Polynomial Kernel
0.9534883720930233
              precision    recall  f1-score   support

           0       0.98      0.94      0.96        53
           1       0.91      0.97      0.94        33

    accuracy                           0.95        86
   macro avg       0.95      0.96      0.95        86
weighted avg       0.96      0.95      0.95        86

[[50  3]
 [ 1 32]]


# 10-FOLD SVM

In [1]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import KFold

kf = KFold(n_splits=10, random_state=42, shuffle=True)

accuracies = []
reports = []
confusion_matrices = []

print("SVC with Polynomial Kernel")

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    
    svm = SVC(kernel='poly', C=3.0, random_state=42)
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)
    
    acc = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    
    accuracies.append(acc)
    reports.append(report)
    confusion_matrices.append(cm)

print("Average accuracy across folds: ", np.mean(accuracies))

for i, report in enumerate(reports):
    print(f"Classification report for fold {i+1}:\n", report)

for i, cm in enumerate(confusion_matrices):
    print(f"Confusion matrix for fold {i+1}:\n", cm)


SVC with Polynomial Kernel


NameError: name 'X' is not defined

# Radial basis function (rbf) kernel:

In [18]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("SVC with RBF Kernel")
svm = SVC(kernel='rbf', C=3.0, random_state=42)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


SVC with RBF Kernel
0.9186046511627907
              precision    recall  f1-score   support

           0       0.96      0.91      0.93        53
           1       0.86      0.94      0.90        33

    accuracy                           0.92        86
   macro avg       0.91      0.92      0.92        86
weighted avg       0.92      0.92      0.92        86

[[48  5]
 [ 2 31]]


In [19]:
#Sigmoid

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("SVC with Sigmoid Kernel")
svm = SVC(kernel='sigmoid', C=3.0, random_state=42)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


SVC with Sigmoid Kernel
0.38372093023255816
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        53
           1       0.38      1.00      0.55        33

    accuracy                           0.38        86
   macro avg       0.19      0.50      0.28        86
weighted avg       0.15      0.38      0.21        86

[[ 0 53]
 [ 0 33]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=3.0, random_state=42)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

SVC
0.8953488372093024
              precision    recall  f1-score   support

           0       0.93      0.87      0.90        46
           1       0.86      0.93      0.89        40

    accuracy                           0.90        86
   macro avg       0.90      0.90      0.90        86
weighted avg       0.90      0.90      0.90        86

[[40  6]
 [ 3 37]]


In [20]:
# decion tree 

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Decision Tree Classifier")
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Decision Tree Classifier
0.7906976744186046
              precision    recall  f1-score   support

           0       0.86      0.79      0.82        53
           1       0.70      0.79      0.74        33

    accuracy                           0.79        86
   macro avg       0.78      0.79      0.78        86
weighted avg       0.80      0.79      0.79        86

[[42 11]
 [ 7 26]]


In [21]:
#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("K-Nearest Neighbors Classifier")
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


K-Nearest Neighbors Classifier
0.9069767441860465
              precision    recall  f1-score   support

           0       0.96      0.89      0.92        53
           1       0.84      0.94      0.89        33

    accuracy                           0.91        86
   macro avg       0.90      0.91      0.90        86
weighted avg       0.91      0.91      0.91        86

[[47  6]
 [ 2 31]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [22]:
#random forest 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Random Forest Classifier")
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Random Forest Classifier
0.872093023255814
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        53
           1       0.79      0.91      0.85        33

    accuracy                           0.87        86
   macro avg       0.86      0.88      0.87        86
weighted avg       0.88      0.87      0.87        86

[[45  8]
 [ 3 30]]


In [23]:
#Logistic Regression 

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Logistic Regression")
lr = LogisticRegression(random_state=42)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Logistic Regression
0.8488372093023255
              precision    recall  f1-score   support

           0       0.90      0.85      0.87        53
           1       0.78      0.85      0.81        33

    accuracy                           0.85        86
   macro avg       0.84      0.85      0.84        86
weighted avg       0.85      0.85      0.85        86

[[45  8]
 [ 5 28]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [24]:
#Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Gradient Boosting Classifier")
gbc = GradientBoostingClassifier(random_state=42)
gbc.fit(X_train, y_train)
y_pred = gbc.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Gradient Boosting Classifier
0.9186046511627907
              precision    recall  f1-score   support

           0       1.00      0.87      0.93        53
           1       0.82      1.00      0.90        33

    accuracy                           0.92        86
   macro avg       0.91      0.93      0.92        86
weighted avg       0.93      0.92      0.92        86

[[46  7]
 [ 0 33]]


In [25]:
#Gaussian Naive Bayes

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Gaussian Naive Bayes")
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Gaussian Naive Bayes
0.8604651162790697
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        53
           1       0.82      0.82      0.82        33

    accuracy                           0.86        86
   macro avg       0.85      0.85      0.85        86
weighted avg       0.86      0.86      0.86        86

[[47  6]
 [ 6 27]]


# K Fold Cross Validations using Combine Original Features

In [52]:
# Import svm from sklearn
from sklearn import svm

# Import cross_val_score and KFold from sklearn's model_selection module.
# cross_val_score is used to evaluate a model using cross-validation.
# KFold is a cross-validation splitter class that provides train/test indices to split data into train/test sets.
from sklearn.model_selection import cross_val_score, KFold

# Import the numpy library, which provides support for arrays  
import numpy as np 

# Create an instance of the SVC (Support Vector Classification) class, which is a type of SVM.
# This classifier will use a linear kernel and a regularization parameter (C) value of 30.
svm_classifier = svm.SVC(kernel='linear',C=30.0)  

# Specify the number of folds to be used in K-Fold Cross-Validation.
num_folds = 5  

# Create an instance of the KFold class with the specified number of splits.
# The data will be shuffled before splitting and the random_state parameter ensures that the shuffling will be the same every time the code is run.
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)

# Calculate cross-validation scores for the SVM classifier.
# This is done by training and testing the model on different subsets of the data, as defined by the K-Fold splitter.
# The target labels are YI, and the features are combined_features.
cv_scores = cross_val_score(svm_classifier, combined_features, YI, cv=kfold)

# Print the accuracy score for each fold.
print("Accuracy Scores for Each Fold:", cv_scores)

# Calculate the average of the cross-validation scores, which gives a single measure of the model's performance.
average_accuracy = np.mean(cv_scores)

# Print the average accuracy.
print("Average Accuracy:", average_accuracy)


Accuracy Scores for Each Fold: [0.91304348 0.89565217 0.87719298 0.9122807  0.85964912]
Average Accuracy: 0.8915636918382912


# Combine CNN Features

In [54]:
dataI=pd.read_csv('Iris.csv')
dataC=pd.read_csv('Conjunctiva.csv')

In [56]:
x1=dataI.drop('Unnamed: 0',axis=1)

In [58]:
x2=dataC.drop('Unnamed: 0',axis=1)

In [60]:
x1

0    1    2    3    4    5    6    7    8    9  ...  36983  36984  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
795  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
796  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
797  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
798  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
799  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

     36985  36986  36987  36988  36989  36990  36991  target  
0      0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
1      0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
2      0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
3      0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
4      0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
..     ...    ...    ...    ...    ...    ...    ...     ...  
795    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
796    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
797    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
798    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
799    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  

[800 rows x 36993 columns]

In [69]:
# Filter rows in the dataframe 'x1' where the 'target' column equals 0.
# This subset represents all data instances where the target value is 0.
# Assign this subset to the variable 'data1'.
data1 = x1.loc[x1['target'] == 0]

# Print the number of rows (length) in 'data1'. 
# This gives us the number of instances in the dataset where the target value is 0.
print(len(data1))

# Filter rows in the dataframe 'x1' where the 'target' column equals 1.
# This subset represents all data instances where the target value is 1.
# Assign this subset to the variable 'data2'.
data2 = x1.loc[x1['target'] == 1]

# Print the number of rows (length) in 'data2'. 
# This gives us the number of instances in the dataset where the target value is 1.
print(len(data2))


400
400


In [70]:
data3=x2.loc[x2['target'] == 0]
print(len(data3))
data4=x2.loc[x2['target'] == 1]
print(len(data4))

286
286


In [71]:
data1=data1[0:286]
data2=data2[0:286]


print(len(data1))
print(len(data2))

286
286


In [72]:
# Use numpy's concatenate function to combine 'data2' and 'data4' along the second axis (axis=1).
# Assuming 'data2' and 'data4' are 2D numpy arrays or compatible structures, 
# this concatenation operation will join the arrays column-wise.

# The output, 'f1', will contain all the rows from both 'data2' and 'data4', 
# where the columns of 'data4' are appended to the right of the columns of 'data2'.
f1 = np.concatenate((data2, data4), axis=1)

# Use numpy's concatenate function to combine 'data1' and 'data3' along the second axis (axis=1).
# Similar to the above operation, this will join 'data1' and 'data3' column-wise.
# The output, 'f0', will contain all the rows from both 'data1' and 'data3', 
# where the columns of 'data3' are appended to the right of the columns of 'data1'.
f0 = np.concatenate((data1, data3), axis=1)


In [77]:
d1=pd.DataFrame(f1)
d0=pd.DataFrame(f0)

In [91]:
dataF=d0.append(d1,ignore_index = True) 
dataF.columns = dataF.columns.astype(str)
dataF

C:\Users\knowl\AppData\Local\Temp\ipykernel_13484\3942030354.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataF=d0.append(d1,ignore_index = True)


0    1    2    3    4    5    6    7    8    9  ...  73976  73977  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
567  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
568  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
569  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
570  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
571  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

     73978  73979  73980     73981  73982  73983  73984  73985  
0      0.0    0.0    0.0  1.377182    0.0    0.0    0.0    0.0  
1      0.0    0.0    0.0  0.000000    0.0    0.0    0.0    0.0  
2      0.0    0.0    0.0  0.000000    0.0    0.0    0.0    0.0  
3      0.0    0.0    0.0  0.000000    0.0    0.0    0.0    0.0  
4      0.0    0.0    0.0  6.356187    0.0    0.0    0.0    0.0  
..     ...    ...    ...       ...    ...    ...    ...    ...  
567    0.0    0.0    0.0  0.000000    0.0    0.0    0.0    1.0  
568    0.0    0.0    0.0  0.000000    0.0    0.0    0.0    1.0  
569    0.0    0.0    0.0  0.000000    0.0    0.0    0.0    1.0  
570    0.0    0.0    0.0  0.000000    0.0    0.0    0.0    1.0  
571    0.0    0.0    0.0  6.905323    0.0    0.0    0.0    1.0  

[572 rows x 73986 columns]

In [92]:
target=dataF['73985']
Feature=dataF.drop('73985',axis=1)

In [93]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Feature, target, test_size=0.15, shuffle=True)

In [94]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=3.0, random_state=42)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

SVC
0.8837209302325582
              precision    recall  f1-score   support

         0.0       0.87      0.87      0.87        39
         1.0       0.89      0.89      0.89        47

    accuracy                           0.88        86
   macro avg       0.88      0.88      0.88        86
weighted avg       0.88      0.88      0.88        86

[[34  5]
 [ 5 42]]


In [95]:
from sklearn import svm
from sklearn.model_selection import cross_val_score, KFold
import numpy as np
# Step 1: Create the SVM classifier
svm_classifier = svm.SVC(kernel='linear',C=30.0)  # You can choose different kernels as well
# Step 2: Perform K-Fold Cross-Validation
num_folds = 5  # Choose the number of folds (k)
# Initialize KFold cross-validator
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)
# Perform cross-validation and get the accuracy scores
cv_scores = cross_val_score(svm_classifier, Feature, target, cv=kfold)
# Print the accuracy scores for each fold
print("Accuracy Scores for Each Fold:", cv_scores)
# Calculate the average accuracy over all folds
average_accuracy = np.mean(cv_scores)
print("Average Accuracy:", average_accuracy)

Accuracy Scores for Each Fold: [0.7826087  0.69565217 0.78947368 0.75438596 0.81578947]
Average Accuracy: 0.767581998474447
